In [2]:
import pandas as pd

df = pd.read_csv("C:\\Users\\muska\\OneDrive\\Desktop\\e commerse project\\esm_E-commerce_Project\\notebooks\\cleaneddata\\ecommerce_transactions_messy.csv")

print("Original Data:")
print(df)

Original Data:
      cust_id               price$  qty#    country product_category  \
0          1.0            Ava Hall  63.0     Mexico         Clothing
1          2.0         Sophia Hall  59.0      India           Beauty
2          3.0     Elijah Thompson  26.0     France            Books
3          4.0        Elijah White  43.0     Mexico           Sports
4          5.0          Ava Harris  48.0    Germany           Beauty
...        ...                 ...   ...        ...              ...
49995  49996.0  Isabella Rodriguez  53.0      India      Electronics
49996  49997.0           Emma Hall  30.0     France              NaN
49997  49998.0      Isabella Allen  50.0  Australia           Beauty
49998  49999.0        Olivia Clark  48.0  Australia          Grocery
49999  50000.0       Olivia Harris  70.0        NaN           Sports

       purchase_amount    payment_method transaction_date
0               780.69        Debit Card       2023-04-14
1               738.56            PayPal       2023-07-30
2               178.34       Credit Card       2023-09-17
3               401.09               UPI       2023-06-21
4               594.83       Net Banking       2024-10-29
...                ...               ...              ...
49995           140.09               UPI       2024-08-07
49996           815.31  Cash on Delivery       2025-02-07
49997           535.77               UPI       2023-08-11
49998           370.99  Cash on Delivery       2025-01-02
49999           577.66       Credit Card       2024-06-03

[50000 rows x 8 columns]

In [3]:
df.head(20)

,cust_id,price$,qty#,country,product_category,purchase_amount,payment_method,transaction_date
0,1.0,Ava Hall,63.0,Mexico,Clothing,780.69,Debit Card,2023-04-14
1,2.0,Sophia Hall,59.0,India,Beauty,738.56,PayPal,2023-07-30
2,3.0,Elijah Thompson,26.0,France,Books,178.34,Credit Card,2023-09-17
3,4.0,Elijah White,43.0,Mexico,Sports,401.09,UPI,2023-06-21
4,5.0,Ava Harris,48.0,Germany,Beauty,594.83,Net Banking,2024-10-29
5,6.0,Elijah Harris,51.0,India,Toys,966.50,Cash on Delivery,2025-01-18
6,7.0,Oliver Clark,27.0,Germany,Home & Kitchen,341.73,Credit Card,2024-03-13
7,8.0,OLIVIA ALLEN,46.0,Canada,Home & Kitchen,11.33,Debit Card,2024-01-04
8,9.0,Liam Harris,54.0,France,Beauty,279.43,Cash on Delivery,2023-12-06
9,10.0,Liam Allen,60.0,Canada,NaN,223.90,Cash on Delivery,2023-08-07
10,NaN,James Clark,NaN,Japan,Home & Kitchen,NaN,Net Banking,2023-08-11
11,12.0,Sophia Allen,48.0,Japan,Grocery,319.74,UPI,2023-11-20
12,13.0,Sophia Harris,21.0,France,Toys,380.15,PayPal,2024-12-10
13,14.0,Sophia Anderson,26.0,France,Toys,871.99,Net Banking,2025-02-05
14,15.0,Ava Thompson,18.0,France,Clothing,382.41,Debit Card,2024-09-28
15,16.0,Elijah Harris,55.0,Australia,Clothing,133.01,Net Banking,2023-12-01
16,17.0,Emma Walker,59.0,Brazil,Electronics,736.55,UPI,2023-08-04
17,18.0,Olivia Harris,47.0,Brazil,Books,336.43,PayPal,2023-05-25
18,19.0,Noah Lewis,20.0,France,Beauty,682.74,PayPal,2025-02-12
19,20.0,James Thompson,43.0,India,Toys,849.67,Cash on Delivery,2023-04-07

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   cust_id           48585 non-null  object
 1    price$           48572 non-null  object
 2   qty#              48582 non-null  object
 3   country           48535 non-null  object
 4   product_category  48499 non-null  object
 5   purchase_amount   48530 non-null  float64
 6   payment_method    48544 non-null  object
 7   transaction_date  48480 non-null  object
dtypes: float64(1), object(7)
memory usage: 3.1+ MB

In [5]:
df.isnull()

,cust_id,price$,qty#,country,product_category,purchase_amount,payment_method,transaction_date
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
49995,False,False,False,False,False,False,False,False
49996,False,False,False,False,True,False,False,False
49997,False,False,False,False,False,False,False,False
49998,False,False,False,False,False,False,False,False
49999,False,False,False,True,False,False,False,False

In [6]:
df.isnull().sum()

cust_id             1415
 price$             1428
qty#                1418
country             1465
product_category    1501
purchase_amount     1470
payment_method      1456
transaction_date    1520
dtype: int64

In [7]:
df.isnull().sum().sum()

print(50000-11673 )

38327

In [8]:
df['payment_method'].value_counts()

payment_method
UPI                 8239
Cash on Delivery    8178
Debit Card          8095
Credit Card         8085
PayPal              7991
Net Banking         7956
Name: count, dtype: int64

In [9]:

# First remove extra spaces from column names
df.columns = df.columns.str.strip()

# rename columns
df.rename(columns={
    'cust_id': 'Customer_ID',
    'price$': 'Customer_Name',
    'qty#': 'Quantity',
    'country': 'Country',
    'product_category': 'Product_Category',
    'purchase_amount': 'Purchase_Amount',
    'payment_method': 'Payment_Method',
    'transaction_date': 'Transaction_Date'
}, inplace=True)

# Check result
print(df.columns)

print(df.head())

Index(['Customer_ID', 'Customer_Name', 'Quantity', 'Country',
       'Product_Category', 'Purchase_Amount', 'Payment_Method',
       'Transaction_Date'],
      dtype='object')
  Customer_ID    Customer_Name Quantity  Country Product_Category  \
0         1.0         Ava Hall     63.0   Mexico         Clothing
1         2.0      Sophia Hall     59.0    India           Beauty
2         3.0  Elijah Thompson     26.0   France            Books
3         4.0     Elijah White     43.0   Mexico           Sports
4         5.0       Ava Harris     48.0  Germany           Beauty

   Purchase_Amount Payment_Method Transaction_Date
0           780.69     Debit Card       2023-04-14
1           738.56         PayPal       2023-07-30
2           178.34    Credit Card       2023-09-17
3           401.09            UPI       2023-06-21
4           594.83    Net Banking       2024-10-29

In [10]:
print(df.dtypes)

Customer_ID          object
Customer_Name        object
Quantity             object
Country              object
Product_Category     object
Purchase_Amount     float64
Payment_Method       object
Transaction_Date     object
dtype: object

In [11]:
# Quantity fix
df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce').fillna(0).astype(int)

# Date fix
df['Transaction_Date'] = pd.to_datetime(df['Transaction_Date'], errors='coerce')

# Check result
print(df.dtypes)

Customer_ID                 object
Customer_Name               object
Quantity                     int64
Country                     object
Product_Category            object
Purchase_Amount            float64
Payment_Method              object
Transaction_Date    datetime64[ns]
dtype: object

In [12]:
df[['Customer_ID','Customer_Name','Payment_Method', 'Product_Category', 'Country']].head()

  Customer_ID    Customer_Name Payment_Method Product_Category  Country
0         1.0         Ava Hall     Debit Card         Clothing   Mexico
1         2.0      Sophia Hall         PayPal           Beauty    India
2         3.0  Elijah Thompson    Credit Card            Books   France
3         4.0     Elijah White            UPI           Sports   Mexico
4         5.0       Ava Harris    Net Banking           Beauty  Germany

In [13]:
df[['Customer_ID','Customer_Name','Payment_Method', 'Product_Category', 'Country']].isnull().sum()

Customer_ID         1415
Customer_Name       1428
Payment_Method      1456
Product_Category    1501
Country             1465
dtype: int64

In [14]:
df[[ 'Quantity','Purchase_Amount','Transaction_Date']].head()

   Quantity  Purchase_Amount Transaction_Date
0        63           780.69       2023-04-14
1        59           738.56       2023-07-30
2        26           178.34       2023-09-17
3        43           401.09       2023-06-21
4        48           594.83       2024-10-29

In [15]:
df[['Quantity','Purchase_Amount','Transaction_Date']].isnull().sum()

Quantity               0
Purchase_Amount     1470
Transaction_Date    1520
dtype: int64

In [16]:
df['Customer_ID'].value_counts()

Customer_ID
unknown    994
NAN         42
UNKNOWN     32
4500.0       2
18800.0      2
          ...
16706.0      1
16707.0      1
16708.0      1
16709.0      1
50000.0      1
Name: count, Length: 47509, dtype: int64

In [17]:
# Fill missing values in Purchase_Amount with the median
df['Purchase_Amount'] = df['Purchase_Amount'].fillna(df['Purchase_Amount'].median())

# Fill missing values in Transaction_Date with the mode (most frequent date)
df['Transaction_Date'] = df['Transaction_Date'].fillna(df['Transaction_Date'].mode()[0])

# Check result
print(df.isnull().sum())

Customer_ID         1415
Customer_Name       1428
Quantity               0
Country             1465
Product_Category    1501
Purchase_Amount        0
Payment_Method      1456
Transaction_Date       0
dtype: int64

In [18]:
# Step 1: Fix Customer_ID (unique serial)
df['Customer_ID'] = range(1, len(df) + 1)

# Step 2: Fill categorical columns with mode (ONLY selected columns)
df['Country'] = df['Country'].fillna(df['Country'].mode()[0])
df['Product_Category'] = df['Product_Category'].fillna(df['Product_Category'].mode()[0])
df['Payment_Method'] = df['Payment_Method'].fillna(df['Payment_Method'].mode()[0])


# Check result
print(df.isnull().sum())

Customer_ID            0
Customer_Name       1428
Quantity               0
Country                0
Product_Category       0
Purchase_Amount        0
Payment_Method         0
Transaction_Date       0
dtype: int64

In [19]:

# remove rows where Customer_Name is NaN
df = df.dropna(subset=['Customer_Name'])

# remove rows where Customer_Name is 'UNKNOWN' or 'unknown'
df = df[~df['Customer_Name'].str.lower().eq('unknown')]

print(df['Customer_Name'].isnull().sum())

0

In [20]:
print(df.isnull().sum())

Customer_ID         0
Customer_Name       0
Quantity            0
Country             0
Product_Category    0
Purchase_Amount     0
Payment_Method      0
Transaction_Date    0
dtype: int64

In [21]:
df.head()

,Customer_ID,Customer_Name,Quantity,Country,Product_Category,Purchase_Amount,Payment_Method,Transaction_Date
0,1,Ava Hall,63,Mexico,Clothing,780.69,Debit Card,2023-04-14
1,2,Sophia Hall,59,India,Beauty,738.56,PayPal,2023-07-30
2,3,Elijah Thompson,26,France,Books,178.34,Credit Card,2023-09-17
3,4,Elijah White,43,Mexico,Sports,401.09,UPI,2023-06-21
4,5,Ava Harris,48,Germany,Beauty,594.83,Net Banking,2024-10-29

In [22]:
df.to_csv("cleaned_data.csv", index=False)